name: Default

on:
  push:
    branches:
      - master
      - 'feature/*'
    tags:
      - 'v*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Java 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Test
        if: success()
        run: ./mvnw clean test
      - name: Package
        if: success()
        run: ./mvnw package
      - name: Build Docker Image
        if: success()
        run: ./mvnw fabric8:build
      - name: Push Docker Image
        if: success()
        run: ./mvnw fabric8:push
        env:
          DOCKER_HUB_USER: ${{ secrets.DOCKER_HUB_USER }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
